apiVersion: v2
name: bionic
description: Bionic - Control plane for AI-agent companies
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - ai
  - agents
  - control-plane
home: https://org.baisoln.com
sources:
  - https://github.com/docker4zerocool/bionic
