apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bionic-org.name" . }}-config
  namespace: {{ .Values.namespace | default .Release.Name }}
  labels:
    {{- include "bionic-org.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  PAPERCLIP_DEPLOYMENT_MODE: {{ .Values.env.PAPERCLIP_DEPLOYMENT_MODE | quote }}
  PAPERCLIP_DEPLOYMENT_EXPOSURE: {{ .Values.env.PAPERCLIP_DEPLOYMENT_EXPOSURE | quote }}
  PAPERCLIP_PUBLIC_URL: {{ tpl .Values.env.PAPERCLIP_PUBLIC_URL . | quote }}
  PAPERCLIP_ALLOWED_HOSTNAMES: {{ tpl .Values.env.PAPERCLIP_ALLOWED_HOSTNAMES . | quote }}
  PAPERCLIP_STORAGE_PROVIDER: {{ .Values.env.PAPERCLIP_STORAGE_PROVIDER | quote }}
  PORT: {{ .Values.env.PORT | quote }}
  SERVE_UI: {{ .Values.env.SERVE_UI | quote }}
  KEYCLOAK_REALM: {{ .Values.env.KEYCLOAK_REALM | quote }}
  KEYCLOAK_URL: {{ tpl .Values.env.KEYCLOAK_URL . | quote }}
  KEYCLOAK_INTERNAL_URL: {{ tpl .Values.env.KEYCLOAK_INTERNAL_URL . | quote }}
  KEYCLOAK_REDIRECT_URI: {{ tpl .Values.env.KEYCLOAK_REDIRECT_URI . | quote }}
  VAULT_ADDR: {{ tpl .Values.env.VAULT_ADDR . | quote }}
  VAULT_K8S_ROLE: {{ tpl .Values.env.VAULT_K8S_ROLE . | quote }}
  MINIO_ENDPOINT: {{ tpl .Values.env.MINIO_ENDPOINT . | quote }}
  MINIO_USE_SSL: {{ tpl .Values.env.MINIO_USE_SSL . | quote }}
  MAIL_FROM: {{ .Values.env.MAIL_FROM | quote }}
  BIONIC_INTERNAL_BASE_URL: {{ .Values.env.BIONIC_INTERNAL_BASE_URL | quote }}
