apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bionic-org.name" . }}
  namespace: {{ .Values.namespace | default .Release.Name }}
  labels:
    {{- include "bionic-org.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.className }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- end }}
    {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  ingressClassName: kong
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bionic-org.name" . }}
                port:
                  number: {{ .Values.service.port }}
