apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default .Release.Name }}
  labels:
    {{- include "bionic-org.labels" . | nindent 4 }}
    velero.io/exclude-from-backup: "false"
    bionic.baisoln.com/gpu-ai-internal: "true"
