apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bionic-org.name" . }}-sa
  namespace: {{ .Values.namespace | default .Release.Name }}
  labels:
    {{- include "bionic-org.labels" . | nindent 4 }}
automountServiceAccountToken: true
